import type { MigrationBuilder } from "node-pg-migrate";

// Library Catalog (AGENTS.md section 32) - a browsable/searchable index
// over devices/'s design-time layout (section 7), rebuilt from the
// filesystem by apps/api/src/libraryCatalog.ts's sync (not a table a
// user edits directly through this app - categories/items are managed by
// moving folders in git, this table is a cache of what's currently
// there).
//
// Two kinds - `device` (devices/standalone/) and `node` (devices/nodes/)
// - deliberately two independent trees, not merged into one (confirmed
// with the user, 2026-08-01 discussion): a Device no longer lives inside
// a Node's own folder (section 7's 2026-08-01 correction) - a Node just
// lists which Device types it's typically paired with (`library_items.
// supports`, sourced from node.yaml's own `supports:` list), a reference,
// not ownership.
export const up = (pgm: MigrationBuilder): void => {
  pgm.createTable("library_categories", {
    id: "id",
    parent_id: {
      type: "integer",
      references: '"library_categories"',
      onDelete: "CASCADE",
    },
    kind: { type: "text", notNull: true, check: "kind in ('device', 'node')" },
    name: { type: "text", notNull: true },
    description: { type: "text" },
    icon_path: { type: "text" },
    // Absolute-from-devices/-root path, e.g. "standalone/thermal" - how
    // the sync matches a folder back to its already-known row across
    // runs, and how it detects a folder that's been renamed/moved
    // (delete-then-recreate rather than trying to infer a rename).
    folder_path: { type: "text", notNull: true, unique: true },
    created_at: { type: "timestamptz", notNull: true, default: pgm.func("now()") },
    updated_at: { type: "timestamptz", notNull: true, default: pgm.func("now()") },
  });

  pgm.createTable("library_items", {
    // Developer-assigned in the DN's own library.json at creation time,
    // never regenerated by sync - the whole point (AGENTS_TO_DO.md,
    // 2026-08-01 discussion: "генеруємо, коли створюємо DN... і він не
    // змінюється потім") is that moving a DN between categories, or even
    // renaming its folder, never loses its catalog identity.
    id: { type: "text", primaryKey: true },
    category_id: {
      type: "integer",
      references: '"library_categories"',
      onDelete: "SET NULL",
    },
    kind: { type: "text", notNull: true, check: "kind in ('device', 'node')" },
    name: { type: "text", notNull: true },
    description: { type: "text" },
    icon_path: { type: "text" },
    folder_path: { type: "text", notNull: true, unique: true },
    // The device-type/node-type name (folder basename, matches
    // devices.type/nodes.type in this same instance's own registry) -
    // separate from `name` (free-text catalog display label) because the
    // two are allowed to diverge; this is what "used in this project"
    // (routes/library.ts) actually joins against.
    type_name: { type: "text", notNull: true },
    // Node items only - array of device type_names this node type is
    // typically paired with (node.yaml's own `supports:` list, section
    // 7/32) - purely informational for the catalog UI, nothing at
    // runtime enforces it.
    supports: { type: "jsonb" },
    last_synced_at: { type: "timestamptz", notNull: true, default: pgm.func("now()") },
    created_at: { type: "timestamptz", notNull: true, default: pgm.func("now()") },
    updated_at: { type: "timestamptz", notNull: true, default: pgm.func("now()") },
  });

  pgm.createIndex("library_items", "category_id");
  pgm.createIndex("library_items", "type_name");
  pgm.createIndex("library_categories", "parent_id");
};

export const down = (pgm: MigrationBuilder): void => {
  pgm.dropTable("library_items");
  pgm.dropTable("library_categories");
};
